FROM ubuntu:14.04

RUN apt-get update && apt-get install -y \
  bc \ 
  cmake \ 
  curl \ 
  gcc-4.6 \ 
  g++-4.6 \ 
  gcc-4.6-multilib \  
  g++-4.6-multilib \ 
  gfortran \ 
  git \ 
  libprotobuf-dev \
  libleveldb-dev \
  libsnappy-dev \
  libopencv-dev \
  libboost-all-dev \ 
  libhdf5-serial-dev \ 
  liblmdb-dev \  
  libjpeg62 \ 
  libfreeimage-dev \  
  libatlas-base-dev \  
  pkgconf \
  protobuf-compiler \ 
  python-dev \  
  python-pip \ 
  unzip \
  wget 

